- hosts: raspberries
  become: yes

  tasks:

    - name: create homer data directory
      file:
        path: "{{ homer_data }}"
        state: directory

    - name: install homer
      docker_container:
        name: homer
        image: b4bz/homer:latest
        restart_policy: unless-stopped
        published_ports:
          - "{{ homer_port }}:8080"
        volumes:
          - "{{ homer_data }}:/www/assets"

    - name: copy homer app icons
      copy:
        src: "tools/"
        dest: "{{ homer_data }}/tools/"

    - name: copy homer dashboard
      ansible.builtin.copy:
        src: "{{ homer_dashboard }}"
        dest: "{{ homer_data }}/config.yml"
