- hosts: raspberries
  become: yes

  tasks:

    - name: create homer data directory
      file:
        path: "{{ homer_data }}"
        state: directory

    - name: install homer
      docker_container:
        name: homer
        image: b4bz/homer:latest
        state: started
        published_ports:
          - "8080:{{ homer_port }}"
        volumes:
          - "{{ homer_data }}:/www/assets"

    - name: copy homer dashboard
      ansible.builtin.copy:
        src: "{{ homer_dashboard }}"
        dest: "{{ homer_data }}/config.yml"
