- hosts: raspberries
  become: yes

  tasks:

    - name: create pihole data directory
      file:
        path: "{{ pihole_data }}"
        state: directory

    - name: install pihole
      docker_container:
        name: pihole
        image: pihole/pihole:latest
        restart_policy: unless-stopped
        network_mode: host
        #published_ports:
        #  - "{{ pihole_port }}:80"
        #  - "53:53/tcp"
        #  - "53:53/udp"
        #  - "67:67/udp"
        env:
          TZ: "Europe/Berlin"
          ServerIP: "192.168.2.6"
          ServerIPv6: "fe80::9ac6:901e:5578:fb31"
          WEBPASSWORD: "pihole"
          #PIHOLE_DNS_: "208.67.222.222;208.67.220.220"
          #DNSMASQ_LISTENING: "all"
          DHCP_ACTIVE: "true"
          DHCP_START: "192.168.2.30"
          DHCP_END: "192.168.2.230"
          DHCP_ROUTER: "192.168.2.1"
          PIHOLE_DOMAIN: "local"
        volumes:
          - "{{ pihole_data }}/pihole/:/etc/pihole"
          - "{{ pihole_data }}/dnsmasq.d/:/etc/dnsmasq.d/"
        capabilities: "NET_ADMIN"
